### PR TITLE
fix #809

### LINKED ISSUE #809: Missing translations for Shift all date options
Hi @dartcafe,

### What is going wrong?
FYI, the `Shift all date options` options <small>(_minute_, _hour_, _day_, _week_, _month_, _year_)</small> are not translated and translatable in [Transifex](https://www.transifex.com/nextcloud/nextcloud/translate/#fr/polls/).

Reference: https://github.com/nextcloud/polls/blob/c7bb4c0b56b1e0269c0b152ac8ecf78bad342fda/src/js/components/SideBar/SideBarTabOptions.vue#L53

**To Reproduce**
1. Change the language setting to another language (e.g. `Français`)
2. Create or open a `Poll schedule` as an admin user
3. Open the right sidebar and click on `Options` tab
4. Open the `Shift all date options` list (`Options pour décaler toutes les dates` in French)
5. See missing translations

**Expected behavior**
Translated options, in French: <small>_minute(s)_, _heure(s)_, _jour(s)_, _semaine(s)_, _mois_, _année(s)_</small>

**Screenshots**
nextcloud_polls_missing_translated_options

### Information about your polls installation
**Polls version?** 1.1.6 (1.2.0-RC seems to have the same issue)

**How did you install this version?** Appstore

### Information about your Instance of Nextcloud/ownCloud
Nextcloud

**Which Version?**

**Nextcloud version:**  18.0.0

Refrence: https://github.com/nextcloud/polls/pull/794#issuecomment-580185203

Have a good day,
Tortue Torche

### PR DESCRIPTION
**Pull request by dartcafe**
fix #809

### CODE REVIEW

File: src/js/components/SideBar/SideBarTabOptionsDate.vue [hunk 1]
```diff
@@ -40,7 +40,11 @@
 			<div>
 				<div class="selectUnit">
 					<input v-model="move.step">
-					<Multiselect v-model="move.unit" :options="move.units" />
+					<Multiselect
+						v-model="move.unit"
+						:options="move.units"
+						label="name"
+						track-by="name" />
```
Comment (v1r0x) [inline src/js/components/SideBar/SideBarTabOptionsDate.vue]: I'd personally use track-by="value" as they are the keys and name is just the rendered label. In this case it doesn't really matter, because they should both be unique.

Comment (dartcafe) [reply src/js/components/SideBar/SideBarTabOptionsDate.vue]: done
