### PR TITLE
Fix test execution paths

### LINKED ISSUE #1387: Cannot run tests with "make test"
### What is going wrong?
**Describe the bug**
Cannot run the tests provided.

**To Reproduce**
1. Download the source code (the latest release is 1.7.5).
2. Run `make test`
3. See the error: `Could not read "phpunit.xml".`

**Expected behavior**
The tests are run correctly.

### Information about your polls installation
Not applicable.

### Information about your Instance of Nextcloud
Not applicable.

### Server configuration
Not applicable.

### Client configuration
Not applicable.

### Logs
See repro steps.

#### Nextcloud log (data/nextcloud.log)
Not applicable.

#### Browser log
Not applicable.

### Working patch
```
diff --git a/Makefile b/Makefile
index f66ef236..4a688113 100644
--- a/Makefile
+++ b/Makefile
@@ -113,5 +113,5 @@ appstore: clean lint build-js-production
 
 .PHONY: test
 test: composer
-	$(CURDIR)/vendor/phpunit/phpunit/phpunit --coverage-clover clover.xml -c phpunit.xml
+	$(CURDIR)/vendor/phpunit/phpunit/phpunit --coverage-clover clover.xml -c tests/phpunit.xml
 	$(CURDIR)/vendor/phpunit/phpunit/phpunit -c phpunit.integration.xml
diff --git a/tests/bootstrap.php b/tests/bootstrap.php
index 5ef2f4c0..09c1d100 100644
--- a/tests/bootstrap.php
+++ b/tests/bootstrap.php
@@ -21,5 +21,5 @@
  *
  */
 
-require_once __DIR__ . '/../../../tests/bootstrap.php';
+require_once __DIR__ . '/bootstrap.php';
 require_once __DIR__ . '/../vendor/autoload.php';
diff --git a/tests/phpunit.xml b/tests/phpunit.xml
index b12b942a..c09aa95b 100644
--- a/tests/phpunit.xml
+++ b/tests/phpunit.xml
@@ -1,4 +1,4 @@
-<phpunit bootstrap="../../../tests/bootstrap.php" colors="true">
+<phpunit bootstrap="./bootstrap.php" colors="true">
     <filter>
         <whitelist>
             <directory suffix=".php">lib</directory>
```

### PR DESCRIPTION
**Pull request by kauron**
I could not get the tests to run correctly, but at least now the tests run. Fixes #1387 

In my case, they fail with `Error: Class 'OC' not found`, even when placed in the `apps` directory of an active Nextcloud installation. Could anyone point me to how to properly run the tests, or where the app should be placed to run these tests?

### CODE REVIEW

**Comment by dartcafe** [comment]
I am struggling with these tests an was happy to get them working for the CI action. Maybe some help can be requested from the nextclouders. @ChristophWurst Any hint, who can assist or help here?

**Comment by dartcafe** [comment]
And to be honest, the tests are terrible limited and do not provide a real value ATM.

**Comment by ChristophWurst** [comment]
> I am struggling with these tests an was happy to get them working for the CI action. Maybe some help can be requested from the nextclouders. @ChristophWurst Any hint, who can assist or help here?

What do you need help with specificallyß

**Comment by dartcafe** [comment]
Hey @ChristophWurst. Thanks for your time.

Due to the fact, that my knowledge is very limited, it could help if someone quality checks the test setup and helps to get this stable. 

Obvioulsy @kauron wasn't able to run the tests locally #1387 and changed the setup, so that it works, but this fails in the CI. 

ATM I am not able to reproduce that, because I am developing in a window environment and didn't have the time/ressources to get familiar with linux subsystem or setting up a dedicated local linux machine.

That's why I could need some help in a correct setup of the tests and to make it run locally and in the CI. Up until now, I got it working with the CI. The currrent setup in the master is a result of try and error and adopting some patterns.

**Review by ChristophWurst — APPROVED** [review]
Changes make sense

**Comment by dartcafe** [comment]
> Changes make sense

Not sure, what you mean. If you mean, that the changes @kauron did, make sense, we have a problem with the CI builds.

**Comment by ChristophWurst** [comment]
does https://github.com/nextcloud/polls/blob/8e8ce349bfc5853081428caa8b71e88bf27be6a4/tests/bootstrap.php#L24 still point to the file from server?

**Comment by dartcafe** [comment]
> does
> still point to the file from server?

I would say yes, but is the leading slash correct? shouldn't it be relative?

**Comment by kauron** [comment]
With my little knowledge of PHP, I'd say that the leading slash separates the directory `__DIR__` from the `..`, so it is required and not an absolute path (`.` joins the two strings).

**Comment by dartcafe** [comment]
So guys, I am completely lost with this test setup. If someone could take a hand on it, so that the tests can be run locally as well with the github actions, I would be happy.

File: tests/bootstrap.php [hunk 1]
```diff
@@ -21,5 +21,5 @@
  *
  */
 
-require_once __DIR__ . '/../../../tests/bootstrap.php';
+require_once __DIR__ . '/bootstrap.php';
```
Comment (ChristophWurst) [inline tests/bootstrap.php:24]: the file requires itself :see_no_evil: 

use ``require_once __DIR__.'/../../../lib/base.php';``

Comment (dartcafe) [reply tests/bootstrap.php]: OMG. Yes. 🤣

**Comment by dartcafe** [comment]
@kauron DOes that solve anything? See last commit...

**Comment by dartcafe** [comment]
As the test work, I will merge this. If more optimizations are neccesary, we should open an new PR.

**Review by dartcafe — APPROVED** [review]
